# Site settings
title: Have You Wandered Every Land
email: hywel.llewellyn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal blog site, with musings about technology and documenting what I learn.
baseurl: "" # the subpath of your site - use "/hywelme" for GitPages and "" for Custom Domain
url: "http://www.hywel.me" # the base hostname & protocol for your site
twitter_username: hywel_llewellyn
github_username:  hyweljohnllewellyn

# Build settings
markdown: kramdown

prose:
  rooturl: ''
  siteurl: 'http://www.hywel.me'
  'media: CURRENT_DATETIME'
  metadata:
    posts:
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          help: "Uncheck to make this post hidden."
          value: true
          on: "true"
          off: "false"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          help: "The blog post title"
          placeholder: "Enter title"
      - name: "date"
        field:
          element: "text"
          label: "Publication Date"
          help: "The publication date for this post."
          placeholder: "Enter date in the form YYYY-MM-DD"
      - name: "allowComments"
        field:
          element: "checkbox"
          label: "Allow Comments"
          help: "Allow users to comment with Disqus."
          value: true
          on: "true"
          off: "false"
  

# Author details.
hywel:
    name: Hywel Llewellyn
    email: rhywel.llewellyn@gmail.com
    web: http://www.hywel.me
