# Site settings
title: Have You Wandered Every Land
email: hywel.llewellyn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal blog site, with musings about technology and documenting what I learn.
baseurl: "" # the subpath of your site - use "/hywelme" for GitPages and "" for Custom Domain
url: "http://www.hywel.me" # the base hostname & protocol for your site
twitter_username: hywel_llewellyn
github_username:  hyweljohnllewellyn

# Build settings
markdown: kramdown

prose:
  rooturl: ''
  siteurl: 'http://www.hywel.me'
  media: 'assets'
  metadata:
    _posts:
      - name: "layout"
        field:
          label: "layout"
          element: "text"
          value: "post"
      - name: "date"
        field:
          label: "date"
          element: "text"
          value: "CURRENT_DATETIME"
      - name: "title"
        field:
          label: "title"
          element: "text"
          placeholder: "Post Title"
          
          
# Author details.
hywel:
    name: Hywel Llewellyn
    email: rhywel.llewellyn@gmail.com
    web: http://www.hywel.me
