# Site settings
title: hywel.me 
email: hello@hywel.me
description: > # this means to ignore newlines until "baseurl:"
  Hi, my name is Hywel Llewellyn. I write about the things I learn so that others can benefit and be successful. I have removed all Google advertising to keep my content as clean and easy to read as possible.
I mainly write about website creation and the resources available, for example, GitHub, WordPress, and Netlify. I also write about other technology when they interest me.
baseurl: "" # the subpath of your site - use "/hywelme" for GitPages and "" for Custom Domain
url: "https://www.hywel.me" # the base hostname & protocol for your site
 #twitter_username: hywel_llewellyn
github_username:  hyweljohnllewellyn

# Build settings
markdown: kramdown

# Github Pages Redirect - https://help.github.com/articles/redirects-on-github-pages/
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Prose.io settings
prose:
  rooturl: ''
  siteurl: 'https://www.hywel.me'
  media: 'assets'
  metadata:
    _posts:
      - name: "layout"
        field:
          label: "layout"
          element: "text"
          value: "post"
      - name: "date"
        field:
          label: "date"
          element: "text"
          value: "CURRENT_DATETIME"
      - name: "author"
        field:
          label: "author"
          element: "text"
          value: "Hywel"
      - name: "categories"
        field:
          label: "categories"
          element: "text"
          placeholder: "Enter categories"
      - name: "title"
        field:
          label: "title"
          element: "text"
          placeholder: "Enter title"
      - name: "excerpt"
        field:
          label: "excerpt"
          element: "text"
          placeholder: "Enter excerpt"
      - name: "meta"
        field:
          label: "meta"
          element: "text"
          placeholder: "Enter metadata"
      - name: "published"
        field:
          label: "published"
          element: "text"
          value: "false"

# Author details.
hywel:
    name: Hywel Llewellyn
    email: hello@hywel.me
    web: https://www.hywel.me
    github: https://github.com/hyweljohnllewellyn